{{$PROMETHEUS_KUBECONFIG_BASE64 := DefaultParam .PROMETHEUS_KUBECONFIG_BASE64 ""}}

apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.46.0
  name: kubeconfig
  namespace: monitoring
type: Opaque
data:
  kubeconfig: {{$PROMETHEUS_KUBECONFIG_BASE64}}
