{{$PROMETHEUS_SCRAPE_KUBELETS := DefaultParam .PROMETHEUS_SCRAPE_KUBELETS false}}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.46.0
  name: prometheus-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 0.46.0
      annotations:
        com.scheduler.port.http: dynamic
        com.scheduler.port.system: dynamic
        com.scheduler.port.grpc: dynamic
        com.scheduler.port.tchannel: dynamic
    spec:
      containers:
      - args:
        {{if $PROMETHEUS_SCRAPE_KUBELETS}}
        - --kubelet-service=kube-system/kubelet
        {{end}}
        - --prometheus-config-reloader=gcr.io/k8s-testimages/quay.io/prometheus-operator/prometheus-config-reloader:v0.46.0
        - --secret-field-selector=type=prometheus-alert
        image: gcr.io/k8s-testimages/quay.io/prometheus-operator/prometheus-operator:v0.46.0
        name: prometheus-operator
        resources:
          limits:
            cpu: 200m
            memory: {{IfThenElse (lt .Nodes 500) 200 400}}Mi
          requests:
            cpu: 200m
            memory: {{IfThenElse (lt .Nodes 500) 200 400}}Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: kubeconfig-volume
          mountPath: /kubeconfig
          readOnly: true
        env:
        - name: KUBECONFIG
          value: /kubeconfig/kubeconfig
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
      hostNetwork: true
      volumes:
      - name: kubeconfig-volume
        secret:
          secretName: kubeconfig
